### ISSUE TITLE
Install w/ Kap 3.0.0 official ?

### ISSUE THREAD

**Issue by Codelica** [ochorocho/kap-nextcloud#4]
Hello!  Just curious if you've tried installing w/ the official Kap 3.0.0 release?  For some reason I'm getting a "Something went wrong while installing nextcloud" message:

<img width="361" alt="Monosnap 2019-11-20 11-43-57" src="https://user-images.githubusercontent.com/386101/69268042-a08a4f80-0b8b-11ea-8b59-660c7103b94d.png">

I couldn't find any Kap logs for further debugging.  If you know of one, let me know. Would love to get this working :) 

Thanks!

**Comment by ochorocho** [comment]
Hey,
thanks for your feedback on the plugin.

What version of Kap do you use?
My version is `3.0.0-beta.6`

I followed the contribution guide, during development dev tools window shows up. It should contain more detailed information when you try to install the plugin.
https://github.com/wulkano/kap/blob/master/contributing.md

currently i'm short on time. But still happy to help when possible.

**Comment by ochorocho** [comment]
Under `/Users/<username>r/Library/Application Support/Kap` you'll find all the Kap data.
There is a folder called `sentry` which contains a log file. I think this could be helpful.

I was able to reproduce the error in 3.0.0 (stable)

Good to know that Kap 3 is now stable. :-)

**Comment by Codelica** [comment]
Thanks for the followup...  install issue was with Kap 3.0.0.  I just tested a new build for them ( [here](https://github.com/wulkano/kap/issues/753#issuecomment-557086478) ) which installs fine.  :)

However after configuring the plugin, I seem to have a problem getting a share link returned:

<img width="359" alt="Banners and Alerts 2019-11-21 09-34-12" src="https://user-images.githubusercontent.com/386101/69357300-151fc580-0c42-11ea-8e6d-3419fa36e170.png">

It uploads the file to my Nextcould server (17.0.1) fine , just seems to have an issue getting a link. I see a PUT to /remote.php (201), and a while later a POST to /ocs/v1.php (200).  But then that alert and no link on the clipboard.  

I tried it with a few different directory configurations (not sure if it matters):

1. not configured for sharing
2. configured as read-only for sharing
3. configured as "File Drop (upload only)

In each case it uploaded the file but after a pretty long delay (timeout?) the Sorry mate alert comes up about the link.   Was just taking a quick look here and it seem Nextcloud 17 uses /ocs/v2.php maybe the call is different.  I'll try to dig in more when I get a chance.

Thanks...

**Comment by Codelica** [comment]
FWIW, I think the issue I'm hitting is related to the `Content-Length` HTTP header being set [here](https://github.com/ochorocho/kap-nextcloud/blob/ca44aa97c4aa75c91084d7cb1e9ac7c4ee65d2bc/index.js#L38-L39)  While it may be valid for the file upload, for the POST to get the link it won't be.  In my case I have NextCloud in Docker behind an NGINX proxy, so it sits waiting for additional content to come and eventually the plugin just times out.   Just changing [this](https://github.com/ochorocho/kap-nextcloud/blob/ca44aa97c4aa75c91084d7cb1e9ac7c4ee65d2bc/index.js#L90) line to use `{'OCS-APIRequest': 'true'}` lets the call complete for me.

**Comment by ochorocho** [comment]
Thanks for investigating. Will try to get a new version out before holidays.

**Comment by ochorocho** [comment]
@Codelica sorry for the delay. Version 1.4.1 should fix the isse.

**Comment by Codelica** [comment]
Thanks!  I gave it a try here.  Uploads work fine now. :)
