### ISSUE TITLE
Nextcloud auth window stuck

### ISSUE THREAD

**Issue by wsoyka** [ochorocho/kap-nextcloud#6]
**Describe the bug**
On first run, when using either auth method (login/app token) the auth window gets stuck. It does save the credentials to the config file, but doesn't close and shows no signs of progress

**To Reproduce**
1. Install kap-nextcloud
2. configure url via settings window
3. create a kapture and share it to Nextcloud
4. Nextcloud auth window opens asking for credentials
5. Enter valid credentials
6. (if using normal login): window changes to show "Grant access" page, click it
5. -> Nextcloud auth window shows no progress and never closes, even though credentials are saved to config file

**Expected behavior**
The window should show if/that the credentials are good, then close

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 10.14.6

**Additional context**
When trying to sign in with invalid credentials the window refreshes and shows the according error.
First discussed over at #5

**Comment by wsoyka** [comment]
**Update**: i think this is either working now or wasn't a real issue in the first place. 

I did some more testing and it seems this only happens when manually removing the credentials from the config file while Kap is running, and trying to re-auth without restarting Kap. 

Not sure if something should be done about this, in any case I wanted to report my findings in case someone runs into this again

**Comment by ochorocho** [comment]
Thanks for reporting. Feel free to re-open if this is still an issue.
